crowdtask/__init__.py
import os
import config
from flask import Flask, url_for, redirect, request
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()

def datetimeformat(value, format='[%Y-%m-%d %H:%M]'):
    return value.strftime(format)

def url_for_other_page(page):
    args = request.view_args.copy()
    args['page'] = page
    return url_for(request.endpoint, **args)

def create_app():

    app = Flask(__name__)
    env = os.getenv('ENV')

    if env == "DEVELOPMENT":
        app.config.from_object('config.DevelopmentConfig')
    elif env == "PRODUCTION":
        app.config.from_object('config.ProductionConfig')
    elif env == "TESTING":
        app.config.from_object('config.TestingConfig')
    elif env == "DEBUG":
        app.config.from_object('config.DebugConfig')
    else:
        app.config.from_object('config.Config')

    app.jinja_env.filters['datetimeformat'] = datetimeformat
    app.jinja_env.globals['url_for_other_page'] = url_for_other_page

    #should put after app
    from crowdtask.views import views
    from crowdtask.api import api
    from crowdtask.task_views import task_views
    from crowdtask.vis_views import vis_views
    from crowdtask.admin_views import admin_views

    app.register_blueprint(views)
    app.register_blueprint(api)
    app.register_blueprint(task_views)
    app.register_blueprint(vis_views)
    app.register_blueprint(admin_views)

    db.app = app
    db.init_app(app)

    with app.app_context():
        # Extensions like Flask-SQLAlchemy now know what the "current" app
        # is while within this block. Therefore, you can now run........
        db.create_all()

    return app

crowdtask/views.py
import re
import random
import string
from flask import Blueprint, Flask, request, render_template, redirect, url_for, jsonify
from crowdtask.dbquery import DBQuery

per_page = 10
views = Blueprint('views', __name__, template_folder='templates')
sample_article = "Gold, a precious metal, is prized for two important characteristics. First of all, gold has a lustrous beauty that is resistant to corrosion. Therefore, it is suitable for jewelry, coins, and ornamental purposes. Gold never needs to be polished and will remain beautiful forever. For example, a Macedonian coin remains as untarnished today as the day it was made 25 centuries ago. Another important characteristic of gold is its usefulness to industry and science. For many years, it has been used in hundreds of industrial applications, such as photography and dentistry. The most recent use of gold is in astronauts' suits. Astronauts wear gold-plated heat shields for protection when they go outside spaceships in space. In conclusion, gold is treasured not only for its beauty but also for its utility."
sample_essay = {
    "title":"Important qualities of a co-worker",
    "content": "We spend more time with our co-workers during weekdays than we do with our family. Thus, it's important for our co-workers to be the people we can get along with. In my opinion, there are certain characteristics that all good co-workers have in common. They are cooperative, considerate and humorous.<BR>We no longer observe now a time that worships individual merits with great enthusiasm. Everyone should cooperate with each other. Teamwork is curial to a business. A good co-worker is willing to contribute to the office community and not too stubborn to accept advice. He realizes the fact that if one's work is left not done in time, it may hold up everyone else.<BR>Besides, a good co-worker is very considerate. He may change his own schedule to accommodate another's emergency. He may be a sympathetic listener, comforting others when they are miserable.<BR>What is more, a good co-worker should have a sense of humor. His positive attitude may create a pleasant environment. When we are under the great stress of work, what we need most is not a delicious meal but merely a few good jokes to relax our nerve cells.<BR>What I have listed is not the complete set of characters of a good co-worker, however, we can feel how comfortable it is to get along with a good co-worker. Being a good co-worker is not difficult but really very necessary. Such ex- perience of being a good co-worker will definitely contribute to other aspects of life such as friendship and a healthy lifestyle."
}

@views.route('/', methods=['GET', 'POST'])
@views.route('/index', methods=['GET', 'POST'])
@views.route('/index/<int:page>', methods=['GET', 'POST'])
def index(page=1):
    paginated_articles = DBQuery().get_article_paginate(page, per_page)
    return render_template('index.html', paginated_articles=paginated_articles)

@views.route('/crowdtask')
def crowdtask():
    return render_template('crowd_index.html')

## should modify sentence split
@views.route('/topic', methods=('GET','POST'))
def topic_task():


    paragraph_idx = None
    article_id = None
    article = None

    worker_id = request.args.get('workerId', u'tester')
    paragraph_idx = request.args.get('paragraph_idx')
    preview_flag = request.args.get('preview_flag')

    if request.args.has_key('article_id'):
        article_id = request.args.get('article_id')
        article = DBQuery().get_article_by_id(article_id)

    #mturk stuff
    assignment_id = request.args.get('assignmentId', u'')
    hit_id = request.args.get('hitId', u'')

    verified_string = generate_verified_str(6)

    if article and preview_flag != "1":
        paragraphs = {}
        for i, paragraph in enumerate(article.content.split("<BR>")):
            if paragraph:
                paragraphs[i] = paragraph

        content = paragraphs.values()
        
        #if paragraph_idx:
        #    paragraph_idx = int(paragraph_idx)
        #    if paragraph_idx and ( paragraph_idx < len(paragraphs.values()) ):
        #        content = [paragraphs[paragraph_idx]]

        data = {
            'worker_id': worker_id,
            'article_id': article_id,
            'title': article.title,
            'content': content,
            'paragraph_idx': paragraph_idx,
            'verified_string': verified_string,
            'hit_id': hit_id,
            'assignment_id': assignment_id
        }
    else:
        data = {
            'worker_id': worker_id,
            'article_id': article_id,
            'title': "Gold",
            'content': [sample_article],
            'paragraph_idx': "",
            'verified_string': verified_string,
            'preview_flag': preview_flag,
            'hit_id': hit_id,
            'assignment_id': assignment_id
        }
    
    return render_template('topic_task.html', data=data)

@views.route('/relevance', methods=('GET','POST'))
def relevance_task():
    article_id = None
    article = None
    paragraph_idx = None

    worker_id = request.args.get('workerId',u'tester')
    paragraph_idx = request.args.get('paragraph_idx')

    
    if request.args.has_key('article_id'):
        article_id = request.args.get('article_id')
        article = DBQuery().get_article_by_id(article_id)

    #mturk stuff
    assignment_id = request.args.get('assignmentId', u'')
    hit_id = request.args.get('hitId', u'')

    verified_string = generate_verified_str(6)

    if article and paragraph_idx:
        paragraph_map = {}
        for i, paragraph in enumerate(article.content.split("<BR>")):
            if paragraph:
                paragraph_map[i] = paragraph

        paragraph_idx = int(paragraph_idx)
        if paragraph_idx >= len(paragraph_map):
            paragraph_idx = 0


        #convert paragraph content to sentence list
        content = paragraph_map[paragraph_idx]
        sentence_list = re.split(r'(?<=[^A-Z].[.?]) +(?=[A-Z])', content)
        par_length = len(sentence_list)

        #if no input, retrieve database
        topic_sentence_idx = None
        if not request.args.has_key('topic_sentence_idx'):
            topics = DBQuery().get_topics_by_article_paragraph_id(article_id, paragraph_idx)
            topic_map = []
            for topic in topics:
                topic_map.extend([int(i) for i in topic.topic_sentence_ids.split(",")])
        
            count_list = [topic_map.count(j) for j in range(par_length)]

            #filter - only keep the max value, and clear up the remaining value
            topic_sentence = [0]*par_length
            

            if max(count_list) >= 2:
                topic_sentence[count_list.index(max(count_list))] = count_list[count_list.index(max(count_list))]
                topic_sentence_idx = count_list.index(max(count_list))
        else:
            if request.args.get('topic_sentence_idx').isdigit():
                topic_sentence_idx = int(request.args.get('topic_sentence_idx'))            
        
        data = {
            'worker_id': worker_id,
            'article_id': article_id,
            'title': article.title,
            'paragraph_idx': paragraph_idx,
            'sentence_list': sentence_list,
            #'topic_sentence': topic_sentence,
            'verified_string': verified_string,
            'hit_id': hit_id,
            'assignment_id': assignment_id,

            #not use yet
            'topic_sentence_idx': topic_sentence_idx
        }
    else:
        #sample
        paragraph_idx = 0
        topic_sentence_idx = 0
        
        topic_map = {}
        topic_sentence_ids = "0"
        topic_map[paragraph_idx] = [int(i) for i in topic_sentence_ids.split(",")]
        
        count_list = []
        sentence_list = []
        
        content = sample_article
        sentence_list = re.split(r'(?<=[^A-Z].[.?]) +(?=[A-Z])', content)
        par_length = len(sentence_list)
        
        if paragraph_idx in topic_map:
            count_list = [topic_map[paragraph_idx].count(j) for j in range(par_length)]
        else:
            count_list = [0]*par_length

        data = {
            'worker_id': worker_id,
            'article_id': article_id,
            'title': "Gold",
            'paragraph_idx': paragraph_idx,
            'sentence_list': sentence_list,
            'topic_sentence': count_list,
            'verified_string': "",
            'preview_flag': "1",
            'hit_id': hit_id,
            'assignment_id': assignment_id,

            'topic_sentence_idx': topic_sentence_idx
        }

    return render_template('relevance_task.html', data=data)
    
@views.route('/relation', methods=('GET','POST'))
def relation_task():
    worker_id = request.args.get('workerId',u'tester')
    paragraph_idx = request.args.get('paragraph_idx', u'0')

    article_id = None
    article = None
    if request.args.has_key('article_id'):
        article_id = request.args.get('article_id')
        article = DBQuery().get_article_by_id(article_id)

    #mturk stuff
    assignment_id = request.args.get('assignmentId', u'')
    hit_id = request.args.get('hitId', u'')

    verified_string = generate_verified_str(6)

    if article:

        paragraph_map = {}
        for i, paragraph in enumerate(article.content.split("<BR>")):
            if paragraph:
                paragraph_map[i] = paragraph

        # set one paragraph (should modify, solved it temporary)
        paragraph_idx = int(paragraph_idx)
        if paragraph_idx >= len(paragraph_map):
            paragraph_idx = 0

        content = paragraph_map[paragraph_idx]
        sentence_list = re.split(r'(?<=[^A-Z].[.?]) +(?=[A-Z])', content)

            
        data = {
            'worker_id': worker_id,
            'article_id': article_id,
            'title': article.title,
            'sentence_list': sentence_list,
            'paragraph_idx': paragraph_idx, #diff from topic

crowdtask/templates/base.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>StructFeed</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="/static/css/normalize.min.css">
        <link rel="stylesheet" href="/static/css/semantic.min.css">
        
        <link rel="stylesheet" href="/static/css/main.css">
        
        
        <script src="/static/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
        {% endblock %}
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% block navbar %}
        <div class="header-container" id="navBar">
            <header class="wrapper clearfix">
                <h1 class="title"><a href="/">StructFeed</a></h1>
                <nav>
                    <ul>
                        <li><a href="/topic">Topic</a></li>
                        <li><a href="/relevance">Relevance</a></li>
                        <li><a href="/relation">Relation</a></li>
                        <li><a href="/link">Link</a></li>
                    </ul>
                </nav>
            </header>
        </div>
        {% endblock %}
        
        <div class="main-container">
            <div class="main wrapper clearfix">
            {% block content %}

                
            {% endblock %}
            </div> <!-- #main -->
        </div> <!-- #main-container -->

        <!--
        <div class="footer-container">
        {% block footer %}
        <footer class="wrapper">
            <p>&copy; 2014 janetyc</p>
        </footer>
        {% endblock %}
        </div>-->

        {% block js %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/static/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <!-- semantic ui theme -->
        <script src="/static/js/vendor/semantic.min.js"></script>


        <script src="/static/js/main.js"></script>
        
        {% endblock %}


        {% block extra_js %}
        {% endblock %}

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID.
        {% block google_analytics %}
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
        {% endblock %}
        -->
    </body>
</html>

crowdtask/templates/clean_base.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>StructFeed</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="/static/css/normalize.min.css">
        <link rel="stylesheet" href="/static/css/semantic.min.css">
        
        <link rel="stylesheet" href="/static/css/main.css">
        <link rel="stylesheet" href="/static/css/range.css">

        <script src="/static/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
        {% endblock %}
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% block navbar %}
        <div class="header-container" id="navBar">
            <header class="wrapper clearfix">
                <h1 class="title"><a href="/">StructFeed</a></h1>
            </header>
        </div>
        {% endblock %}
        
        <div class="main-container">
            <div class="main wrapper clearfix">
            {% block content %}

                
            {% endblock %}
            </div> <!-- #main -->
        </div> <!-- #main-container -->

        <!--
        <div class="footer-container">
        {% block footer %}
        <footer class="wrapper">
            <p>&copy; 2014 janetyc</p>
        </footer>
        {% endblock %}
        </div>-->

        {% block js %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/static/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <!-- semantic ui theme -->
        <script src="/static/js/vendor/semantic.min.js"></script>
        <script src="/static/js/main.js"></script>
        
        <script src="/static/js/components/range.js"></script>
        {% endblock %}


        {% block extra_js %}
        {% endblock %}

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID.
        {% block google_analytics %}
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
        {% endblock %}
        -->
    </body>
</html>

crowdtask/templates/closepopup.html
{% extends "mturk_base.html" %}
{% block title %} - Returning to Mechanical Turk{% endblock %}
{% block content %}
<div class="success-area">
  <h2>Thanks for Your Contribution</h2>
  <hr/>
  <div class="text-description">
    <p>Please <b>close this windows</b> and <b>go back to the original page in the Mechanical Turk.</b></p>
    <p>Then, try to <b>refresh the HIT page</b> and you will see the <b>Complete button</b> in the HIT submission page.</p>
    <p>Finally, please press <b>Complete button</b> and finsih the task.</p>
  </div>
</div>
{% endblock %}

crowdtask/templates/complete.html
{% extends "mturk_base.html" %}
{% block title %} - Thanks Page for WritingFeedback Experiment{% endblock %}
{% block content %}
<div class="complete-area">
<h1>Thanks for your participation</h1>
<div clas="text-description" id="debriefingtext">
    <p>Thanks again for your participation in our study!</p>
    <p>To complete the HIT, simply press the button below.</p>
    {% if data.using_sandbox %}
        <form id="mturk_form" action="https://workersandbox.mturk.com/mturk/externalSubmit" method="post">
    {% else %}
        <form id="mturk_form" action="https://www.mturk.com/mturk/externalSubmit" method="post">
    {% endif %}
    <input type="hidden" id="assignmentId" name="assignmentId" value="{{ data.assignment_id }}"  /> 
    <input type="hidden" id="hitId" name="hitId" value="{{ data.hit_id }}"  /> 
    <input type="hidden" id="workerId" name="workerId" value="{{ data.worker_id }}"  /> 
    <input class="ui button green" id="submitButton" type="submit" name="Submit" value="Complete HIT"  /> 
    </form>
</div>
</div>
{% endblock %}

crowdtask/templates/crowd_index.html
{% extends "base.html" %}
{% block content %}

<section>
    <div class="center-area">
    <div class="ui three column grid stackable">
        <div class="column">
            <div class="ui fluid card">
                <div class="image">
                    <img src="/static/images/identify.png">
                </div>
                <div class="content">
                    <a class="header">Identify Task</a>
                </div>
            </div>
        </div>
    
        <div class="column">
            <div class="ui fluid card">
                <div class="image">
                    <img src="/static/images/highlight.png">
                </div>
                <div class="content">
                    <a class="header">Highlight Task</a>
                </div>
            </div>
        </div>
        <div class="column">
            <div class="ui fluid card">
                <div class="image">
                    <img src="/static/images/classify.png">
                </div>
                <div class="content">
                    <a class="header">Classify Task</a>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
{% endblock %}

crowdtask/templates/error.html
{% extends "base.html" %}
{% block title %} - Page Not Found{% endblock %}
{% block content %}
    {% if errornum == 1010 %}
    <h4> 
        <p>Sorry, our records indicate that you have already completed (or attempted to complete) this hit before.<p>
        <p>Because this is a experiment, participants can only complete this hit for limited times.</p>
        <p>Please release the hit so that someone else can perform the experiment.</p>
        <p>Thank you!</p>
    </h4>        
    {% else %}
    	<h4> 
    	    <p>Sorry, there was an unexpected error in our processing of your hit.<p> 
    	    <p>Please email <a href="janetyc@gmail.com">janetyc@gmail.com</a><br/>
    	    and send the following information:</p>
    	</h4>
	    <div>
	        <h4>
	        Error: #{{ errornum }}<br>
            {{ errordesc }}
	        {% if hitid %} HitI: #{{ hitid }}<br> {% endif %}
	        {% if assignid %}AssignId: #{{ assignid }}<br> {% endif %}
	        {% if workerid %} WorkerId: #{{ workerid }}<br> {% endif %}
	        </h4>
	    </div>
	    <h4><p>Our sincere apologies!</p></h4>
    {% endif %}
{% endblock %}

crowdtask/templates/experiment.html
{% extends "base.html" %}
{% block content %}
<header>Show Experiment Articles</header>
<section>
    <ul>
    {% for subject in data %}
    <li>{{subject}}: {{data[subject]["name"]}}
        {% for version_id, article_id in data[subject]["data"] %}
            [<a href="{{ url_for('views.show_article', article_id=article_id)}}">{{version_id}}:{{article_id}}</a>](<a href="{{ url_for('admin_views.groundtruth', article_id=article_id)}}">annotate</a>)(<a href="{{ url_for('admin_views.get_groundtruth_json', article_id=article_id)}}">json</a>)
        {% endfor %}
    </li>
    {% endfor %}
    </ul>
</section>
{% endblock %}

crowdtask/templates/groundtruth.html
{% extends "base.html" %}
{% block content %}
<span><a href="{{ url_for('views.show_all')}}">All Articles</a> > Article {{ data.article_id}}</span>
<div class="article-title">{{ data.title }} ({{data.authors}})</div>
<div>
    {% for golden in data.all_goldens %}
        <a href="{{ url_for('admin_views.groundtruth', article_id=data.article_id)}}?golden_id={{golden}}">{{golden}}</a>
    {% endfor %}
    (<a href="{{ url_for('admin_views.get_groundtruth_json', article_id=data.article_id)}}">json</a>)
</div>

<div class="ui buttons" id="annotate-type">
  <button class="ui button active">Topic</button>
  <button class="ui button">Irrelevance</button>
  <button class="ui button">Relevance</button>
</div>

<div class="ui input right-block">
  <input id="annotator-name" type="text" placeholder="Input the name...">
</div>
<div id="working-area" class="content">
    {% for paragraph_idx in data.content_map %}
    <p class="paragraph" id="paragraph_{{ paragraph_idx }}">
        {% for sentence_idx in range(data.content_map[paragraph_idx]|length) %}
        {% if data.topic_map[paragraph_idx][sentence_idx] %}
        <span id="sentence_{{sentence_idx}}" class="sentence highlight-sentence highlight">
        {% elif data.irrelevance_map[paragraph_idx][sentence_idx] %}
        <span id="sentence_{{sentence_idx}}" class="sentence highlight-sentence irrelevance">
        {% else %}
        <span id="sentence_{{sentence_idx}}" class="sentence highlight-sentence">
        {% endif %}
            {% for word in data.content_map[paragraph_idx][sentence_idx].strip().split(" ") %}
                {% if word %}
                    {% if data.relevance_map[paragraph_idx][sentence_idx][loop.index-1] %}
                    <span class="basic-word relevance" id="word_{{loop.index-1}}">{{word}}</span>
                    {% else %}
                    <span class="basic-word" id="word_{{loop.index-1}}">{{word}}</span>
                    {% endif%}
                {% endif %}    
            {% endfor %}
            <!--{{data.content_map[paragraph_idx][sentence_idx]}}-->
        </span>
        {% endfor %}
    </p>
    {% endfor %}
</div>
<div class="submit-area" id="submitTask">
    <div id="submitAnswer" class="ui button green">Submit</div>
</div>
{% endblock %}


{% block extra_js %}
<script>
    $(function() {
        $current_type = $(".ui.button.active").text();
        //hide loading image
        $('#loading-image').hide();

        //highlight selection
        $('.highlight-sentence').click(function(){
            if($current_type == "Topic"){
                $(this).toggleClass('highlight');
            }
            if($current_type == "Irrelevance"){
                $(this).toggleClass('irrelevance');
            }
        });
        $('.basic-word').click(function(){
            if($current_type == "Relevance"){
                $(this).toggleClass('relevance');
            }
        });
        
        
        $('#annotate-type .ui.button').click(function(){
            $('#annotate-type .ui.button').removeClass('active');
            $(this).addClass('active');
            $current_type = $(this).text();
            if($current_type == "Topic"){
                console.log("Topic");
                $(".sentence").addClass("highlight-sentence");
                $(".basic-word").removeClass("word");
            }
            if($current_type == "Irrelevance"){
                console.log("Irrelevance");
                $(".sentence").addClass("highlight-sentence");
                $(".basic-word").removeClass("word");
            }
            if($current_type == "Relevance"){
                console.log("Relevance");
                $(".sentence").removeClass("highlight-sentence");
                $(".basic-word").addClass("word");
            }
            
        });

        //submit answer to server
        $("#submitAnswer").click(function(event){

            // retrieve all topic sentences
            var topicArray = new Array();
            $('.highlight').each(function(j){
                var sentence_id = $(this).closest('.sentence').attr('id').split("_");
                var paragraph_id = $(this).closest('.paragraph').attr('id').split("_");
                topicArray.push(paragraph_id[1]+"-"+sentence_id[1]); 
            });

            var irrelevanceArray = new Array();
            $('.irrelevance').each(function(j){
                var sentence_id = $(this).closest('.sentence').attr('id').split("_");
                var paragraph_id = $(this).closest('.paragraph').attr('id').split("_");
                irrelevanceArray.push(paragraph_id[1]+"-"+sentence_id[1]); 
            });


            // retrieve all relevance area
            var relevanceArr = new Array();
            $("#working-area .relevance").each(function(i){
                var word_id = this.id.split("_");
                var sentence_id = $(this).closest('.sentence').attr('id').split("_");
                var paragraph_id = $(this).closest('.paragraph').attr('id').split("_");

                relevanceArr.push(paragraph_id[1]+"-"+sentence_id[1]+"-"+word_id[1]);
            });

            
            var resultTopic = "";
            resultTopic = topicArray.join("|");
            //console.log("topic-->"+resultTopic);

            var resultRelevance = "";
            resultRelevance = relevanceArr.join("|");
            //console.log("relevance-->"+resultRelevance);

            var resultIrrelevance = "";
            resultIrrelevance = irrelevanceArray.join("|");

            $.ajax({
                type: "GET",
                url: "/api/add_golden_structure",

                data: {
                    "article_id": "{{ data.article_id }}",
                    "golden_topic": resultTopic,
                    "golden_relevance": resultRelevance,
                    "golden_irrelevance": resultIrrelevance,
                    "created_user": $("#annotator-name").val()
                },
                

                dataType: 'json', 
                beforeSend: function(){
                    $('#loading-image').show();
                },
                complete: function(){
                    $('#loading-image').hide();
                },
                success: function(data) {
                    window.location = "/success";
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    alert("Error");    
                }
            });
        });
        
    });
</script>
{% endblock %}

crowdtask/templates/mturkindex.html
{% extends "mturk_base.html" %}
{% block title %} - Returning to Mechanical Turk{% endblock %}
{% block content %}
    {% if assignmentId == "ASSIGNMENT_ID_NOT_AVAILABLE" %}
        <p>you haven't accept this mturk</p>
        {% else %}
		<script>
			function openwindow() {
				
				url = "/welcome?{{param|urlencode|safe}}";
				
				
                popup = window.open(url,'Popup','toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=no,width='+screen.availWidth+',height='+screen.availHeight+'');
				
				popup.onunload = function() { location.reload(true) }
			}
		</script>
		<h1>Thank you for accepting this HIT!</h1>
		<p>By clicking the following URL link, you will be taken to the experiment,
				including several questions. After completing all the tasks, we will bring you back to the mturk page</p>

		<p>
		Please disable pop-up blockers before continuing.
		</p>
		<p><a class="ui button green" href="#" onClick="openwindow()">Click here to start</a></p>

    {% endif %}
{% endblock %}

crowdtask/templates/success.html
{% extends "base.html" %}
{% block title %} - Success!{% endblock %}
{% block content %}
<div class="success-area">
  <h1>Thanks for Your Contribution!</h1>
  {% if data.verified_string %}
  <p>Please copy verified code: <span class="verified-code">{{ data.verified_string }}</span>, and paste it to the answer field in Mturk page.</p>
  {% endif %}
  <p><a href="{{ url_for('views.index') }}">Home</a></p>
</div>
{% endblock %}